routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['namespace' => 'Auth'], function () {
    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
});

Route::get('/', 'HomeController@blog')->name('blog');

Route::get('/category', 'HomeController@categoryList')->name('category-list');

Route::get('/{slug}', 'HomeController@articleDetail')->name('article-detail');

Route::get('/category/{slug}', 'HomeController@categoryDetail')->name('category-detail');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

    // Dashboard
    Route::get('/dashboard', 'DashboardController@dashboard')->name('dashboard');

    //Admin routes  article
    Route::get('/articles', 'ArticleCrudController@index')->name('article-index');

    Route::get('/articles/create', 'ArticleCrudController@create')->name('article-create');
    Route::post('/articles/store', 'ArticleCrudController@store')->name('article-store');

    Route::get('/articles/{id}/edit', 'ArticleCrudController@edit')->name('article-edit');
    Route::post('/articles/{id}', 'ArticleCrudController@update')->name('article-update');

    Route::get('/articles/{id}/delete', 'ArticleCrudController@destroy')->name('article-destroy');


    //Admin routes  categories
    Route::get('/admin/categories', 'CategoryCrudController@index')->name('category-index');

    Route::get('/admin/categories/create', 'CategoryCrudController@create')->name('category-create');
    Route::post('/admin/categories/store', 'CategoryCrudController@store')->name('category-store');

    Route::get('/admin/categories/{id}/edit', 'CategoryCrudController@edit')->name('category-edit');
    Route::post('/admin/categories/{id}', 'CategoryCrudController@update')->name('category-update');

    Route::get('/admin/categories/{id}/delete', 'CategoryCrudController@destroy')->name('category-destroy');

    Route::get('/admin/user', 'UserController@index')->name('user-index');
    Route::get('/admin/user/create', 'UserController@create')->name('user-create');
    Route::post('/admin/user/store', 'UserController@store')->name('user-store');
    Route::get('/admin/user/{id}/edit', 'UserController@edit')->name('user-edit');
    Route::post('/admin/user/{id}', 'UserController@update')->name('user-update');
    Route::get('/admin/user/{id}/delete', 'UserController@destroy')->name('user-destroy');
    Route::get('/admin/user/{id}/profile', 'UserController@show')->name('user-show');
});

resources/views/partial/footer.blade.php
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                              <i class="fas fa-circle fa-stack-2x"></i>
                              <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                              <i class="fas fa-circle fa-stack-2x"></i>
                              <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                              <i class="fas fa-circle fa-stack-2x"></i>
                              <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                              <i class="fas fa-circle fa-stack-2x"></i>
                              <i class="fas fa-envelope fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                              <i class="fas fa-circle fa-stack-2x"></i>
                              <i class="fas fa-globe fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; <a href="#">Blogku.co</a> {{ date('Y') }}</p>
            </div>
        </div>
    </div>
</footer>

resources/views/partial/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ route('blog') }}">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">
             Blog Admin
        </div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{{ route('admin.dashboard') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Blog
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="far fa-newspaper"></i>
            <span>Articles</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{{ route('admin.article-create') }}">
                    Add new Article
                </a>
                <a class="collapse-item" href="{{ route('admin.article-index') }}">
                    List Articles
                </a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseCategories" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-tag"></i>
            <span>Categories</span>
        </a>
        <div id="collapseCategories" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{{ route('admin.category-create') }}">
                    Add new Category
                </a>
                <a class="collapse-item" href="{{ route('admin.category-index') }}">
                    List Categories
                </a>
            </div>
        </div>
    </li>


    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-user"></i>
            <span>Users</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{{ route('admin.user-create') }}">
                    Add new User
                </a>
                <a class="collapse-item" href="{{ route('admin.user-index') }}">
                    List Users
                </a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->